# We have 2 stage Test and Deploy
stages:
  - test
  - deploy

# Config cache
cache:
  paths:
    - node_modules/

# Test job
test:
  # Docker image
  image: node:latest
  # Attach Test job to Test stage
  stage: test
  # Config to use GitLab Shared Runner with Executor Docker
  tags:
    - docker
  script:
  #  - npm install --legacy-peer-deps
    - npm install
  # Defines the names of branches and tags the job runs for
  only:
    - production

# Deploy job
deploy:
  type: deploy
  # Attach Deploy job to Deploy stage
  stage: deploy
  before_script:
    - whoami
    - export PATH=/home/node-applications/.nvm/versions/node/v14.17.3/bin:$PATH
  # Config to use our Runner with Executor Shell
  tags:
    - micro-frontend
  script:
    # Only copy changed files to project folder
    - cp -r -u * /home/node-applications/frontend-app/
    - cd /home/node-applications/frontend-app/
    - ls -la
    - echo "PATH='${PATH}'"
    - rm -rf node_modules
    - npm install
    - npm run production
    # Restart NodeJS service
    - pm2 restart frontend-app
  only:
    - production